name: singularity-deploy

on: 
  workflow_dispatch

jobs:
  release:
    permissions: write-all
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3
      - name: Build the singularity container
        run: |
            repo=$(echo "${GITHUB_REPOSITORY/\//-}")

            singularity build --fakeroot lem.sif lyceanem.def
            if [ "$?" == "0" ]; then
                echo "Successfully built container lem.sif."                
            else
                echo "There was an issue building lem.sif."          
            fi
      
